version: '2.13' # specify docker-compose version
 
# Define the services/ containers to be run
services:
  angular: # name of the first service
    build: ./app-spa # specify the directory of the Dockerfile
    ports:
      - "4200:80" # specify port mapping
    # volumes:
    #   - "/app-spa/node_modules"
    #   - ".:/app-spa"

  node: # name of the second service
    build: ./app-server # specify the directory of the Dockerfile
    ports:
      - "8080:8080" # specify port mapping
    depends_on:
      - mongo # specify the dependency of the service
    environment:
      - MONGO_URL=mongodb://mongo:27017/Schtocc-PROD # specify the environment variable
  
  mongo: # name of the database service
    image: mongo:latest
    ports:
      - 27016:27017
    volumes:
      - ./mongo:/data/db